spring.application.name=KinalApp
server.port=8081

#Conexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dbclientes_in5am?createDatabaseIfNotExist=true
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am

#JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true
spring.thymeleaf.cache=false

spring.security.user.name=admin
spring.security.user.password=admin

# Redirigir / a /login
spring.security.oauth2.client.provider.keycloak.issuer-uri=